import PlanOptions from "@/components/SignUp/PlanOptions";
import SignUpFooter from "@/components/SignUp/SignUpFooter";
import SignUpHeader from "@/components/SignUp/SignUpHeader";
import useAuth from "@/hooks/useAuth";
import { CheckIcon } from "@heroicons/react/24/solid";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react"

const benefitList = [
  "Watch all you want. Ad-free.",
  "Recomendations just for you.",
  "Change or cancel your plan anytime",
];

export default function Planform() {
  const [choosenPlan, setChoosenPlan] = useState("basic");
  const router = useRouter()
  const { changeUserPlan } = useAuth()

  const choosePlanhandler = async () => {
    await changeUserPlan(choosenPlan)
    router.push('/')
  }

  return (
    <div>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SignUpHeader route="/id-en" label="Sign Out" />
      <main className="bg-white text-[#333] pb-[95px]">
        <div className="px-4 pt-5 pb-[60px] mb-[15px] max-w-[978px] mx-auto">
          <section className="px-4">
            <p className="text-[13px] ">STEP 2 OF 3</p>
            <h1 className="text-[32px] font-medium leading-[1.25] mb-[0.4em]">
              Choose the plan that{"'"}s right for you.
            </h1>
            <ul className="mt-1 mb-4 font-light">
              {benefitList.map((item) => (
                <li key={item} className="flex">
                  <CheckIcon className="h-[26px] w-[26px] min-w-[26px] text-[#e50914]" />
                  <p className="ml-2.5 mt-1.5 text-left shrink text-[19px] leading-6">
                    {item}
                  </p>
                </li>
              ))}
            </ul>
          </section>

          <PlanOptions choosenPlan={choosenPlan} setChoosenPlan={(plan) => setChoosenPlan(plan)}/>

          <div className="px-4 mt-6 text-center">
            <button
            onClick={choosePlanhandler}
              type="submit"
              className="w-full py-[20.5px] px-[2em] text-2xl leading-[1] bg-[#e50914] text-white rounded hover:cursor-pointer max-w-[440px]"
            >
              Next
            </button>
          </div>
        </div>
        
      </main>
      <SignUpFooter />
    </div>
  );
}
