import { authState } from "@/atoms/modalAtoms";
import SignUpFooter from "@/components/SignUp/SignUpFooter";
import SignUpHeader from "@/components/SignUp/SignUpHeader";
import useAuth from "@/hooks/useAuth";
import Head from "next/head";
import { useRouter } from "next/router";
import { FormEvent, useState } from "react";
import { SubmitHandler, useForm } from "react-hook-form";
import { useRecoilState } from "recoil";

interface Inputs {
  email: string;
  password: string;
}

export default function SignupRegform() {
  const [auth, setAuth] = useRecoilState(authState);
  const [emailFill, setEmailFill] = useState(auth.email !== '')
  const [passFill, setPassFill] = useState(auth.password !== '')
  const { signUp } = useAuth()
  const {
    register,
    handleSubmit,
    formState: { errors },
    getValues
  } = useForm<Inputs>();

  const router = useRouter();

  if (auth.email === "") {
    router.push("/id-en");
    return null;
  }

  const onSubmit: SubmitHandler<Inputs> = async ({ email, password }) => {
    router.push("/signup");
    setAuth({ email: email, password: password });
    await signUp( email, password )
  };

  const changeHandler = (event: FormEvent) => {
    event.preventDefault()
    const emailValue = getValues('email')
    const passValue = getValues('password')
    if (emailValue === '') {
      setEmailFill(false)
    } else {
      setEmailFill(true)
    }

    if (passValue === '') {
      setPassFill(false)
    } else {
      setPassFill(true)
    }
  }

  return (
    <div>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignUpHeader route="/login" label="Sign In" />
      <main className="bg-white min-h-[calc(100vh-292px)] sm:min-h-[calc(100vh-286.5px)] md:min-h-[calc(100vh-266px)]">
        <div className="pb-[95px] max-w-[440px] box-content mx-auto">
          <form
            className="text-[#333333] pt-5 pb-[60px] px-8 sm:px-0 mb-[15px]"
            onSubmit={handleSubmit(onSubmit)}
            onChange={changeHandler}
          >
            <p className="text-[13px] mt-5">STEP 1 OF 3</p>
            <h1 className="text-[32px] font-medium leading-[1.25] mb-[0.4em]">
              Create a password to start your membership
            </h1>
            <p className="text-[18px] leading-6">
              Just a few more steps and you{"'"}re done!
            </p>
            <p className="text-[18px] leading-6 mt-2.5">
              We hate paperwork, too.
            </p>
            <div className="mt-4 mb-5">
              <div className="relative mb-2.5">
                <input
                  defaultValue={auth.email}
                  type="email"
                  className="peer pt-2.5 px-2.5 w-full border border-[#8c8c8c] text-lg sm:text-[1.25rem] text-black h-[60px] md:h-[60px] xl:h-[70px] rounded focus:outline-none"
                  {...register("email", { required: true })}
                />
                <label className={`absolute text-[#8c8c8c] left-2.5 -translate-y-1/2 peer-focus:text-xs peer-focus:top-3 ${emailFill ? "text-xs top-3 md:text-xs md:top-4" : "text-sm top-1/2"} transition-all ease-linear md:text-base md:peer-focus:top-4`}>
                  Email
                </label>
              </div>
              <div className="relative mb-2.5">
                <input
                  type="password"
                  className="peer pt-2.5 px-2.5 w-full border border-[#8c8c8c] text-lg sm:text-[1.25rem] text-black h-[60px] md:h-[60px] xl:h-[70px] rounded focus:outline-none"
                  {...register("password", { required: true })}
                />
                <label className={`absolute text-[#8c8c8c] left-2.5 -translate-y-1/2 peer-focus:text-xs peer-focus:top-3 ${passFill ? "text-xs top-3 md:text-xs md:top-4" : "text-sm top-1/2"} transition-all ease-linear md:text-base md:peer-focus:top-4`}>
                  Add a password
                </label>
              </div>
            </div>

            <p className="text-[#0071eb] text-base font-light">
              Forgot your password?
            </p>
            <button
              type="submit"
              className="mt-6 w-full py-[20.5px] px-[2em] text-2xl leading-[1] bg-[#e50914] text-white rounded hover:cursor-pointer"
            >
              Next
            </button>
          </form>
        </div>
      </main>
      <SignUpFooter />
    </div>
  );
}
