import SignUpFooter from "@/components/SignUp/SignUpFooter";
import SignUpHeader from "@/components/SignUp/SignUpHeader";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";

export default function Regristration() {
    const router = useRouter()

  return (
    <div>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SignUpHeader route="/login" label="Sign In" />

      <main className="bg-white pb-[95px] text-base text-[#333] min-h-[calc(100vh-292px)] sm:min-h-[calc(100vh-286.5px)] md:min-h-[calc(100vh-266px)]">
        <div className="pt-5 px-8 pb-[60px] mx-auto mb-[15px]">
          <div className="max-w-[340px] mx-auto">
            <Image
              src="https://shrtco.de/DRtHmx"
              alt="register"
              width={150}
              height={150}
              className="w-[260px] h-[90px] mt-[100px] mb-5 object-contain sm:mx-auto"
            />
            <p className="text-[13px] sm:text-center">STEP 1 OF 3</p>
            <h1 className="text-[32px] sm:text-center font-medium leading-[1.25] mb-[0.4em]">
              Finish setting up your account
            </h1>
            <p className="text-[18px] max-w-[300px] sm:text-center sm:mx-auto">
              Netflix is personalized for you. Create a password to watch on any
              device at any time.
            </p>
          </div>
          <div className="text-center mt-6">
            <button onClick={() => router.push("/signup/regform")} className="w-full py-[20.5px] px-[2em] max-w-[340px] text-2xl leading-[1] bg-[#e50914] text-white rounded hover:cursor-pointer">
              Next
            </button>
          </div>
        </div>
      </main>

      <SignUpFooter />
    </div>
  );
}
