import useAuth from "@/hooks/useAuth";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Account() {
  const { user, userData, logout } = useAuth();
  const date = new Date(Date.now() + 3600 * 24 * 30);
  const dateArray = date.toString().split(" ");

  return (
    <div className="bg-white min-h-screen">
      <Head>
        <title>Account Settings- Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="bg-[#141414] flex justify-between items-center h-[45px] sm:h-[75px] md:h-[90px]">
        <Image
          src="https://shrtco.de/I8XtQq"
          className="cursor-pointer h-5 w-[75px] ml-[3%] sm:h-[45px] sm:w-[167px]"
          width={150}
          height={150}
          alt="netflix"
        />

        <Link href="/account">
          <Image
            src="https://rb.gy/g1pwyx"
            alt="profile"
            className="cursor-pointer rounded h-6 w-6"
            width={100}
            height={100}
          />
        </Link>
      </header>

      <main className="pt-20 md:pt-32 text-[#333] mx-auto max-w-6xl px-5 pb-12 transition-all md:px-10">
        <div className="flex flex-col gap-x-4 md:flex-row md:items-center">
          <h1 className="text-3xl md:text-4xl">Account</h1>
          <div className="-ml-0.5 flex items-center gap-x-1.5">
            <Image
              src="/assets/icons/membersince.svg"
              width={50}
              height={50}
              alt="member"
              className="h-7 w-7"
            />
            <p className="text-xs font-semibold text-[#737373]">
              Member since {user?.metadata.creationTime}
            </p>
          </div>
        </div>

        <div className="mt-6 grid grid-col-1 gap-x-4 border px-4 py-4 md:grid-cols-4 md:border-x-0 md:border-t md:border-b-0 md:px-0 md:pb-0">
          <div>
            <h4 className="text-lg text-[#737373]">Membership & Billing</h4>
            <button className="h-10 w-full whitespace-nowrap bg-gray-200 py-2 text-sm font-medium shadow-md hover:bg-gray-200 md:w-4/5">
              Cancel Membership
            </button>
          </div>
          <div className="col-span-3">
            <div className="flex flex-col justify-between border-b py-4 md:pt-0 md:flex-row">
              <div>
                <p className="font-medium">{userData?.email}</p>
                <p className="text-[#737373]">Password: *******</p>
              </div>
              <div className="md:text-right">
                <p className="cursor-pointer text-[#0071eb] hover:underline">
                  Change email
                </p>
                <p className="text-[#0071eb] hover:underline cursor-pointer">
                  Change password
                </p>
              </div>
            </div>

            <div className="flex flex-col justify-between pt-4 pb-4 md:flex-row md:pb-0">
              <div>
                <p>
                  Your membership will end on{" "}
                  {dateArray[0] +
                    ", " +
                    dateArray[2] +
                    " " +
                    dateArray[1] +
                    " " +
                    dateArray[3] +
                    " " +
                    dateArray[4] +
                    " GMT"}
                </p>
              </div>
              <div className="md:text-right">
                <p className="text-[#0071eb] hover:underline cursor-pointer">
                  Manage payment info
                </p>
                <p className="text-[#0071eb] hover:underline cursor-pointer">
                  Add backup payment method
                </p>
                <p className="text-[#0071eb] hover:underline cursor-pointer">
                  Billing details
                </p>
                <p className="text-[#0071eb] hover:underline cursor-pointer">
                  Change billing day
                </p>
              </div>
            </div>
          </div>
        </div>

        <div className="mt-6 grid grid-col-1 gap-x-4 border px-4 py-4 md:grid-cols-4 md:border-x-0 md:border-t md:border-b-0 md:px-0 md:pb-0">
          <h4 className="text-lg text-[#737373]">Plan Details</h4>

          <div className="capitalize col-span-2 font-medium">{userData?.subscription}</div>
          <p className="cursor-pointer text-[#0071eb] hover:underline hover:cursor-pointer md:text-right">
            Change plan
          </p>
        </div>

        <div className="mt-6 grid grid-col-1 gap-x-4 border px-4 py-4 md:grid-cols-4 md:border-x-0 md:border-t md:border-b-0 md:px-0 md:pb-0">
          <h4 className="text-lg text-[#737373]">Settings</h4>
          <p
            className="col-spans-3 cursor-pointer text-[#0071eb] hover:underline"
            onClick={() => logout()}
          >
            Sign out of all devices
          </p>
        </div>
      </main>
    </div>
  );
}
