import Header from "@/components/Header";
import Row from "@/components/Row";
import useAuth from "@/hooks/useAuth";
import { Movie } from "@/typings";
import Head from "next/head";
import { useEffect, useState } from "react";

const API_KEY = process.env.NEXT_PUBLIC_API_KEY;

interface Show {
  id: string;
  media: string;
}

export default function MyList() {
  const { userData } = useAuth();
  const [myListData, setMyListData] = useState<Movie[]>([]);

  useEffect(() => {
    if (userData) {
      setMyListData([]);
      const fetchMyList = () => {
        userData.personalShows.map(async (item: Show) => {
          await fetch(
            `https://api.themoviedb.org/3/${
              item.media === "tv" ? "tv" : "movie"
            }/${
              item.id
            }?api_key=${API_KEY}&language=en-US&append_to_response=videos`
          ).then(async (res) => {
            const data = await res.json();
            setMyListData((prev) => {
              return [...prev, data];
            });
          });
        });
      };

      fetchMyList();
    }
  }, [userData]);

  return (
    <div className="relative h-screen bg-gradient-to-b from-gray-900/10 to-[#010511] lg:h-[140vh]">
      <Head>
        <title>My List - Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="relative pl-4 py-20 pb-24 lg-space-y-24 lg:pl-16">
        <Row title="My List" movies={myListData} />
      </main>
    </div>
  );
}
